name: Deploy to Production

on:
  push:
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Debug SSH connection
      run: |
        echo "Host: ${{ secrets.SERVER_HOST }}"
        echo "User: ${{ secrets.SERVER_USER }}"
        echo "Key length: ${#SERVER_SSH_KEY}"
        # Don't print the actual key for security
      env:
        SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}      
    - name: Simulate Build and push (static site)
      run: |
        cd src
        cd components
        
    - name: Copy test files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: ".,!frontend/HelpBox.jsx"  # Copy everything except frontend build
        target: "/opt/my-app/test"
        debug:true
    - name: Confirm deployment
      run: echo "Deployment complete."